In [1]:
import re
import numpy as np

LINE_PATTERN = re.compile(r"(\d+),(\d+) -> (\d+),(\d+)")

In [4]:
with open('test_input.txt', 'r') as f:
    lines = [LINE_PATTERN.match(l).groups() for l in f]

In [5]:
a = np.fromiter(iter(lines), dtype='int,int,int,int')

In [9]:
a.view()

array([(0, 9, 5, 9), (8, 0, 0, 8), (9, 4, 3, 4), (2, 2, 2, 1),
       (7, 0, 7, 4), (6, 4, 2, 0), (0, 9, 2, 9), (3, 4, 1, 4),
       (0, 0, 8, 8), (5, 5, 8, 2)],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8')])

In [10]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
def parse_input(filepath):


        a = (
            
            .view(np.int32)
            .reshape(-1, 4)
        )


    return a

In [12]:
def sym_arange(start, stop):
    if stop > start:
        return np.arange(start, stop + 1)
    else:
        return np.arange(stop, start-1, step=-1)

In [13]:
sym_arange(1, 5)

array([1, 2, 3, 4, 5])

In [14]:
sym_arange(5, 1)

array([], dtype=int64)

In [15]:
np.arange(5, 1, step=-1)

array([5, 4, 3, 2])